#!/usr/bin/env node

// goes to bare
// pushes to local storage
// hopefully executed on push command



const fs = require('fs');
const { join } = require("path")

let testpath = ".git/objects/"
let defStoragePath = "../../Storage/"
let excptList = ["info", "pack"]


function ListFiles(testFolder){
  let files = []
  fs.readdirSync(testFolder).forEach(file => {
    if( excptList.indexOf(file) > -1){
    }else {
      files = [... files, file]
      // console.log(file);
    }
  });

  return files
}


function GetObjectsName(objHomeDirectory) {
  let names = []
  let dirs = ListFiles(objHomeDirectory)
  dirs.forEach(d => {
    files = ListFiles(objHomeDirectory + d + "/")
    files.forEach(f => {
      names = [...names, d + f]
    })
  })

  return names;
}

function CopyObjects(namesList = [],pulling = true, storagePath = defStoragePath){
  let localObjsPath = "objects/"
  if (!pulling){
    let temp = storagePath
    storagePath = localObjsPath
    localObjsPath = temp
  }

  console.log(storagePath)
  console.log(localObjsPath)
  let localObjs = GetObjectsName(storagePath)
  let missing = []

  if (namesList.length > 0){
    namesList.forEach(n => {
      if(localObjs.indexOf(n) <= -1){
        missing = [...missing, n]
      }
    })
  }{
    missing = localObjs
  }

  console.log(localObjs)
  console.log(missing)

  missing.forEach( m => {
    if (!fs.existsSync(localObjsPath + m.substring(0,2))){
      fs.mkdirSync(localObjsPath + m.substring(0,2));
    }
    if(!fs.existsSync(localObjsPath + m.substring(0,2) + "/" + m.substring(2))){
      fs.copyFileSync(storagePath + m.substring(0,2) + "/" + m.substring(2), localObjsPath + m.substring(0,2) + "/" + m.substring(2)
      // , (err) => {
      // if (err) throw err;
      // console.log(m + " was added to bare repo");
      // }
    );
    }
  })
}

CopyObjects([], false)
